### ISSUE TITLE
Trusted root certificates for CMG still needed

### ISSUE THREAD

**Issue by MarcoCibis** [MicrosoftDocs/memdocs.de-de#1]
This feature is great and extends the capabilities! Still a trusted certificate is needed to access the CMG. In case you use your own CA don't forget to publish the internal trusted root certificate to the client. Is there any way of including this cert in the token to m minimize administrative overhead?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 60a7510b-10d9-e7e2-f848-d57d69d7fe10
* Version Independent ID: d4e9a557-ca23-3727-52b8-b81c6f767757
* Content: [Tokenbasierte Authentifizierung für CMG - Configuration Manager](https://docs.microsoft.com/de-de/mem/configmgr/core/clients/deploy/deploy-clients-cmg-token#feedback)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md](https://github.com/MicrosoftDocs/memdocs.de-de/blob/live/memdocs/configmgr/core/clients/deploy/deploy-clients-cmg-token.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by srvbpigh** [comment]
Hello, @MarcoCibis
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by aczechowski** [comment]
Hi @MarcoCibis, yes, this doesn't otherwise change the requirements for CMG. I suggest filing your suggestion on UserVoice so that the product team can consider the idea of including the trusted root certificate with the token.
#please-close
